### ISSUE TITLE
Transformer Changes

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#109]
The current preprocessing script has a few issues that deviate from expected behavior.

There is a "file_byte_limit" that takes on a default value of ~1MB, while the input files range from 30-300MB. This results in an extremely small subsampling of lines from the input files to generate the vocabulary.

After the vocab been built to consist of the set of unique tokens from the subset of the input, it is whittled down to approximately the user-specified vocab size by using a bisection method. While this looks to be deterministic, it does not provide the user with the vocab size requested and is unlikely to be a convenient size (e.g., 32768).

The vocab size generated in preprocessing is different than the size indicated (hard-coded) in the model_params.py file.

A proposed method would sample the entire set of input files to generate the vocab, and perform a top-k operation based on number of occurrences (e.g., collections.counter.most_common(target_vocab_size)) to return exactly the requested vocab size. Additionally to improve performance by minimizing padding required, the preprocessor could optionally sort the data by sequence length, create batches, and then shuffle the frozen batches. This would serve to group similar length sequences into the same batch to require less padding.

**Comment by bitfort** [comment]
SWG:

Revisit over email or in next meeting. Talk to engineers if you're submitting to get an opinion on the impact of this change. Furtherer information about performance and convergence will be provided.

**Comment by tremblerz** [comment]
I also agree with the value of `file_byte_limit` being used as ~1MB for reading tokens to build vocabulary. Since a lower value will not be a good representative for tokens in the whole file. The current way of constructing tokens allows passing `min_count` by which we can set up a threshold of minimum occurrence of any token to get added into the vocabulary file, hence changing the parameter would cover the proposed method. Also, the bisection based search method is deterministic and makes vocabulary file to the closest possible number of target_vocab_size (which is 32768 right now). Fixing upon target_vocab_size is necessary from this perspective as it controls the overall number of parameters in the embedding layer and hence the final model. If we decide to search other for some other value of target_vocab_size then essentially we will have to do the search manually and then hardcode it in model_params.py.

Regarding next point, if I have not got it wrong, minimizing padding for improved performance is already implemented [here](https://github.com/mlperf/training/blob/master/translation/tensorflow/transformer/utils/dataset.py). It basically allocates every sample to a fixed number of buckets based on their length and creates the batch accordingly. This preprocessing also takes care of discarding aberrantly large samples (could be either training sample or target sample or both) which is 256 right now iirc.

**Comment by bitfort** [comment]
SWG:

We expect a PR to be circulated over email for review for this bug fix.

**Comment by bitfort** [comment]
SWG:

We want to have an immediate follow up meeting to discuss; will summarization the exact proposal on the mailing list with the specific changes. We ask everyone interested to follow and engage with the mailing list on this issue for swift resolution.

**Comment by petermattson** [comment]
Can we defer to 5.1? Would need the most impressive data ever. Email sooner if possible.

**Comment by tremblerz** [comment]
I tried to vary file_byte_size and seems like the target_vocab_size does not have any impact on the final number of subtokens. See the attached figure for tokens vs file_byte_limit.

I think this is due to a bug in tokenizer.py, I had sent one PR for the fix here https://github.com/mlperf/training/pull/64/

<img width="744" alt="screen shot 2018-10-30 at 10 39 30 am" src="https://user-images.githubusercontent.com/10557215/47700672-54493600-dc3d-11e8-9ce5-4fb6fd7faf60.png">

**Comment by petermattson** [comment]
SWG:
Decided to return to in 5.1 and figure out vocab size.

**Comment by petermattson** [comment]
Moving to training repo issue
