### ISSUE TITLE
how to deal with the same predictions in NCF evaluate?

### ISSUE THREAD

**Issue by qiuxin2012** [mlcommons/training_policies#131]
For example, our test positive(userID: 100, prediction: 0.9) and test negative(userID: 200, prediction: 0.9) are both in the 10th place. But our prediction only use the first 10, so how to deal with this case? Who is the 11th, userID 100 or userID 200?

**Comment by petermattson** [comment]
SWG:
Any decision is acceptable given the low probability. 

( Then go buy a lottery ticket. :-) )

**Comment by codyaustun** [comment]
@petermattson order is important for the test positive example. I believe the test positive example should always come last if there is a tie to match the [reference](https://github.com/mlperf/training/blob/5cc0d7a5137e271c950915e2f3557220b4dc0400/recommendation/pytorch/ncf.py#L89) and the [NCF author's original implementation](https://github.com/hexiangnan/neural_collaborative_filtering/blob/0cd2681598507f1cc26d110083327069963f4433/evaluate.py#L58). Previously, I ran into issues where the hit rate was significantly higher because the test positive example always won ties. For example, imagine a model that reports the same value for everything; the model's hit rate would be 100% even though it didn't learn anything. I don't have the data readily available, but I can reproduce if need be.
