### ISSUE TITLE
Same graph 

### ISSUE THREAD

**Issue by Keno** [mlcommons/training_policies#141]
The rules for the closed division currently state:

```
Benchmark implementations must use the same graph as the reference implementation.
```

We were planning to submit benchmark results utilizing Julia's Flux framework, which does not have a graph (everything is done on julia IR). The rules seems a bit ill defined (e.g. one could consider the julia CFG to be Flux's "graph"). We'd of course be happy to make sure that the model is mathematically equivalent to the reference implementation.

**Comment by robieta** [comment]
To the best of my knowledge your interpretation is correct. The point of that rule is just so that everyone is performing the same task, not to preclude submissions which choose to implement the benchmark in a specific way. If you haven't already, I would highly suggest that you reach out to @petermattson who would be happy to make sure you're clear on the closed rules.

**Comment by petermattson** [comment]
Hi Keno, Please do contact me ASAP. The closed rules evolved rapidly and we should make sure your expectations are aligned. petermattson@google.com. Thanks!

**Comment by David-Levinthal** [comment]
how are the graphs generated to prove consistency?
without that I am not sure this rule actually has any meaning
:-)

**Comment by petermattson** [comment]
Believe this should be closed.
