### ISSUE TITLE
Initialization overhead 

### ISSUE THREAD

**Issue by petermattson** [mlcommons/training_policies#186]
Google suggest: clock start before "touch data" not "touch data and touch model"
SWG request: 
1. What are we not timing
2. Some data to show this matters
3. Where would clock start go in reference implementations

**Comment by bitfort** [comment]
SWG Notes:

Conceptually -- make small benchmarks on large machines give meaningful results which suggest performance of large benchmarks on large machines. This enables us to keep benchmarks small (and low cost) while allowing large systems to demonstrate their performance in a meaningful way. 

Possible options include a "budget" of initialization, where you don't pay for initialization within budget. This budget could be based on a static number, the size of the system, and/or the size of the dataset/model. Ideally this budget could consume the existing MPI exceptions. 

AI(NV) -- Come back with more thoughts on this.

**Comment by bitfort** [comment]
SWG Notes:

General consensus is that we want to change timing rules instead of making benchmarks bigger. When we do this, we want to ensure that submissions and scores reflect common practice (and not doing unusual work during the untimed initialization phase). 

One proposed implementation of this is to create a "budget" of time which can be spent in initialization. We would expect this budget is sufficient to encompass common practice. 

We generally agree that the clock must start before using training data. 

AI(NV & Everyone else) - Find a concrete number for a budget.

**Comment by bitfort** [comment]
SWG Notes:

AI(NV & Everyone) - Offer concrete numbers.

**Comment by bitfort** [comment]
SWG Note:

Discussion:
- Training sessions are various lengths, some as fast as half an hour; perhaps quick training jobs can turn off graph compilation if it is too much overhead. 
- Gather data and choose a liberal time window for the next few rounds, possibly with agreement to revise with new data.
- Proposal to scale budget with size of system (and model size).
- Could be useful to have a single budget for all systems (instead of scaling the budget). 
- We've observed that compilation time scales up with system and model size. 

It seems one particular issue is to avoid submitters "gaming" the benchmark using this budget. Using a formula which scales with system size could help mitigate this concern.

**Comment by bitfort** [comment]
SWG Notes:

This was discussed in STWG last week.

We will adopt the initialization budget concept with a budget of 20 minutes -- specifically, any time initialization which exceeds 20 minutes will be added to the MLPerf score. 
At a high level, initialization time is from work interacting with the model (to be defined in a future SWG meeting); initialization ends and benchmark time begins when you touch data; benchmark time ends once an evaluation completes which hits target accuracy. Exact definitions of these events will be defined in a future SWG. 

The choice of 20 minutes is considered subject to change given data to support such a change. We also generally recognize that we intend to adjust this budget to suit the needs to submitters (subject to supporting evidence).
