### ISSUE TITLE
Reference code finalization prior to submission

### ISSUE THREAD

**Issue by jonathan-cohen-nvidia** [mlcommons/training_policies#246]
All references should have any changes in PR for 4 months before submission, and PRs merged in 3 months before submission. Changes should include:
- Any functional changes to the reference
- Support for all possible batch sizes and other hyper parameter settings, as well as any batching schemes
- Proper logging

Reason:
Timeline for getting changes to cuDNN (or other vendor libraries) and frameworks into an official release as per MLPerf requirements for Closed division submission is about 2 months from code complete.  So any development in a vendor library takes (say) 1 month.  That means one would like a code complete reference implementation to tune for 3 months prior to release.

**Comment by bitfort** [comment]
SWG Notes:

This sounds like it describes a mature benchmark. There is a spectrum of approaches to work towards this. 

A few options:
- One option is to give a "drop deadline" where all changes are dropped after this deadline.
- Another option is to have people "vote" or share expectations as to if something is stable, so we can at least narrow things down and set expectations. 

To explore:

Have two buckets, "stable" and "experimental". We have some procedure to put "things" (benchmark level? scale level?) into buckets. Expectation is clear, but what happens if someone wants to change something stable near the deadline? How would this impact how we report results? What is the bar to change a stable benchmark. 

AI(Everyone) - Think on the questions above.

**Comment by bitfort** [comment]
This has been handled the best we could for v0.7.
