### ISSUE TITLE
DLRM - Exploring current optimizer for convergence with large batch sizes (512K) 

### ISSUE THREAD

**Issue by rnaidu02** [mlcommons/training_policies#288]
Intel team is evaluating the current optimizer (SGD) for convergence with large batch size for DLRM on multi node. If the convergence issues are not resolved, would like to try a different optimizer. Intel would like to seek the decision on updated optimizer by Apr 24 (3 weeks from now).

**Comment by bitfort** [comment]
SWG:

Nvidia has looked at up to 16k, this could be an interesting place to start. It would be interesting to get to 512k batch size; there are a few questions:
- Is there evidence you share that shows under the current rules we cannot converge at 512k (such as failed rules and the HPs tried).
- In order to look at new optimizer, we would be interested in seeing a proposal from Intel or another submitter which shows how this can be done.

**Comment by bitfort** [comment]
SWG:

We added poly decay to DLRM to achieve some larger batch sizes. Can continue to revisit thsi in future rounds.
