### ISSUE TITLE
[translation] Discussion To Remove Preprocessing (Sharding+Tokenization) From Timing

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#53]
Moving rules question from https://github.com/mlperf/reference/issues/109:

The preprocessing stage requires a non-negligible fraction of the overall execution time, especially as models are optimized. It seems like timing this portion may not be representative of real-world use cases since the cost of preprocessing in this situation is not amortized over multiple training sessions. I would vote to remove the timing around preprocessing, but I would like to see if there is a good reason for keeping it.

**Comment by TheKanter** [comment]
1. We should record this information, as it's quite useful. More information is better.

2. If we don't count pre-processing, then this will incentivize everyone to do maximal pre-processing to keep actual training short and simple. Do we believe this is representative? Is this good?

3. It seems to me that if we want to truly measure end-to-end latency, we need pre-processing.

4. Your point about pre-processing is that in 'real world' scenarios, pre-processing is a smaller proportion of the overall problem than in the MLPerf tests because 'real world' you train multiple times on the same data set.  MLPerf is a first attempt to get things right, we don't need to be perfect initially.

**Comment by ddkang** [comment]
Why is translation different from, say, image classification?

**Comment by bitfort** [comment]
This issue is complicated and we will revisit this issue next week.

**Comment by petermattson** [comment]
See issue 30 for v0.5 policy.

**Comment by petermattson** [comment]
Closed as covered by issue #30.
