### ISSUE TITLE
NCF: Lazy Adam for Embeddings

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#80]
This is a request to allow for NCF to use the LazyAdam optimizer for embeddings (the reference uses Adam).

**Comment by codyaustun** [comment]
Is this a reference change or just a rules change?

**Comment by bitfort** [comment]
No reference change, Adam is still allowed. This would just be to expand and allow the use of Lazy Adam.

**Comment by robieta** [comment]
To add some data, I did 11 (because that's what finished overnight) runs with both Adam and LazyAdam. I fixed the seed and hashed the pipeline so I guarantee that the two algorithms see the same examples in the same order. The variation that I see between the two optimizers is comparable to what I see with fixed seed and identical code:

Detailed (epoch by epoch) hit rates.
[NCF_LazyAdam_Results.txt](https://github.com/mlperf/policies/files/2402457/NCF_LazyAdam_Results.txt)

Adam misses: 3
LazyAdam misses: 4

**Comment by robieta** [comment]
Oh, also worth noting is the average number of epochs for those that did converge.
Adam: 8.875
LazyAdam: 9.0

So well within the variance of NCF.

**Comment by bitfort** [comment]
SWG:

Tentatively okay. Will confirm next meeting.

**Comment by bitfort** [comment]
SWG:

Closing as duplicate of separate Adam/Lazy Adam issue.

**Comment by delock** [comment]
> SWG:
> 
> Closing as duplicate of separate Adam/Lazy Adam issue.

Is lazy adam accepted?   Can you post the link to the original issue? Thanks! @bitfort
